### PR TITLE
costa: send signal instead of ipc to destroy client

### LINKED ISSUE #561: training failed，训练cancel 之后训练进程没有退出
image

### PR DESCRIPTION
**Pull request by FeelyChau**
Fix #561 .
Costa sends the destroy-request by IPC, if the client is busy, i.e. training loop in boa stack, the request will not be processed util the `nextTick`, so it will not exit immediately. But we can use signal to make sure the client process can receive it when the OS switches the process from sleeping to running.

### CODE REVIEW

**Comment by yorkie** [comment]
@FeelyChau Could you please explain a bit why this PR fixes #561?

File: packages/costa/src/runnable.ts [hunk 1]
```diff
@@ -176,7 +176,7 @@ export class PluginRunnable {
       return;
     }
     this.canceled = true;
-    this.send(PluginOperator.WRITE, { event: 'destroy' });
+    this.handle.kill('SIGHUP');
```
Comment (yorkie) [inline packages/costa/src/runnable.ts:179]: SIGTERM?

Comment (yorkie) [reply packages/costa/src/runnable.ts:179]: And shall we have a retry with the signal when detecting the costa process is busy?

Comment (FeelyChau) [reply packages/costa/src/runnable.ts:179]: Is there any case we need to wait the client process ends itself? If not , signal will be more quick and directly.

Comment (FeelyChau) [reply packages/costa/src/runnable.ts:179]: If we need to wait something done, I think we could handle the signal in client and do the ends, it seems more elegantly.

File: packages/costa/src/runnable.ts [hunk 2]
```diff
@@ -18,6 +18,8 @@ export class RunnableResponse implements PluginResponse {
   }
 }
 
+// wait 1000ms for chile process finish.
+const waitForDestroied = 1000;
```
Comment (yorkie) [inline packages/costa/src/runnable.ts:22]:
```suggestion
const waitForDestroyed = 1000;
```

File: packages/costa/src/runnable.ts [hunk 3]
```diff
@@ -47,7 +49,8 @@ export class PluginRunnable {
   private onread: Function | null;
   private onreadfail: Function | null;
   private ondestroyed: Function | null;
-
+  // timer for wait the process to exit itself
+  private termTimer: NodeJS.Timeout;
```
Comment (yorkie) [inline packages/costa/src/runnable.ts:53]:
```suggestion
  private notRespondTimer: NodeJS.Timeout;
```

File: packages/costa/src/runnable.ts [hunk 4]
```diff
@@ -252,6 +260,9 @@ export class PluginRunnable {
    */
   private async afterDestroy(code: number, signal: NodeJS.Signals): Promise<void> {
     debug(`the runnable(${this.id}) has been destroyed with(code=${code}, signal=${signal}).`);
+    if (this.termTimer) {
+      clearTimeout(this.termTimer);
```
Comment (yorkie) [inline packages/costa/src/runnable.ts:264]: this.notRespondTimer = null;

**Review by yorkie — CHANGES_REQUESTED** [review]

**Review by yorkie — APPROVED** [review]

**Review by rickycao-qy — APPROVED** [review]
Looks good to me
